# Generated by Django 4.1.1 on 2022-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=None, upload_to='authors'),
        ),
    ]
