# Generated by Django 4.1.1 on 2022-09-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
