# Generated by Django 4.1.1 on 2022-10-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='arabic', max_length=255),
        ),
    ]
