# Generated by Django 4.1.1 on 2022-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_confirm_email',
            field=models.BooleanField(default=False),
        ),
    ]
